apiVersion: v2
name: google-cas-issuer
description: Google CAS Issuer — cert-manager plugin for GCP Certificate Authority Service
type: application
version: 1.0.0

# Check latest: helm search repo jetstack/google-cas-issuer --versions
# Add repo: helm repo add jetstack https://charts.jetstack.io
dependencies:
  - name: google-cas-issuer
    version: "0.7.0"
    repository: https://charts.jetstack.io
