apiVersion: v2
name: google-cas-issuer
description: Google CAS Issuer — cert-manager plugin for GCP Certificate Authority Service
type: application
version: 1.0.0

# Check latest:
#   helm repo add jetstack https://charts.jetstack.io
#   helm search repo jetstack/cert-manager-google-cas-issuer --versions
dependencies:
  - name: cert-manager-google-cas-issuer
    version: "0.11.0"
    repository: https://charts.jetstack.io
