apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/elayaraja-kv/k8s-as-code.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: "app-{{path.basename}}"
      labels:
        cluster: stg-iac-01-ause2
        type: app
    spec:
      project: default
      source:
        repoURL: https://github.com/elayaraja-kv/k8s-as-code.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
